#! python


def build(ctx):




    for reg in 'lasso', 'fused', 'fusion':
        for sim in 'blocks_levels', 'blocks_few_spikes', 'blocks_many_spikes', 'spikes':

            ctx(
                features='run_py_script',
                source='data_generation.py',
                deps=ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(sim)),
                target=ctx.path_to(ctx, 'OUT_ANALYSIS', 'data_{}_{}.pickle'.format(reg,sim)),
                append=[reg, sim]
            )
