#! python

import os

def build(ctx):

    abspath = os.path.join(ctx.path.abspath(),'test_fused_lasso.py')
    ctx(
        features='run_py_script',
        source='test_fused_lasso.py',
        deps=[ctx.path_to(ctx, 'IN_MODEL_CODE', 'fused_lasso_lagrange.py'),
              ctx.path_to(ctx, 'IN_MODEL_CODE', 'fused_lasso_primal.py'),
              ctx.path_to(ctx, 'IN_MODEL_CODE', 'flestimator.py')
             ],
        append=abspath
    )
