#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 18 11:55:21 2019
@author: clara
"""

import scipy
from tabulate import tabulate
import pickle
import numpy as np
"""Load analysis data"""

for reg in 'lasso', 'fused', 'fusion':
    for sim in 'one_block', 'blocks', 'blocks_levels', 'blocks_spikes':
        with open(ppj("OUT_ANALYSIS", "analysis_{}_{}.pickle".format(reg,sim)), "rb") as in12_file:
            analysis = pickle.load(in12_file)


zeros_mean = analysis[0]
zeros_stf = analysis[1]

ones_mean = analysis[2]
ones_std = analysis[3]

spikes_mean = analysis[4]
spikes_std = analysis[5]

blocks_mean = analysis[6]
blocks_std = analysis[7]







rowIDs = ["Mean","Standarterror"]
headers = ["Zerors", "Relevant", "Spikes", "Blocks"]

table = tabulate(np.reshape(analysis,(2,4),'F'), headers, tablefmt="latex_booktabs", floatfmt=".2f", showindex=rowIDs)
text_file = open("Output.txt", "w")
text_file.write(table)
text_file.close()
print(tabulate(a, tablefmt="latex_booktabs", floatfmt=".2f"))


with open("/home/christopher/Dokumente/rm_fused_lasso/bld/out/analysis/analysis_fused_one_block.pickle", "rb") as in12_file:
    analysis = pickle.load(in12_file)
np.shape(analysis)
